// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from './src/config/env.js';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'src/database/prisma/schema.prisma',
    migrations: {
        path: 'src/database/prisma/migrations',
    },
    datasource: {
        url: config.DATABASE_URL,
    },
});
